export const LOAD_BLOGCOMMENTS_STARTED = 'LOAD_BLOGCOMMENTS_STARTED';
export const LOAD_BLOGCOMMENTS_SUCCEEDED = 'LOAD_BLOGCOMMENTS_SUCCEEDED';
export const LOAD_BLOGCOMMENTS_FAILED = 'LOAD_BLOGCOMMENTS_FAILED';

export const LOAD_POSTCOMMENTS_STARTED = 'LOAD_POSTCOMMENTS_STARTED';
export const LOAD_POSTCOMMENTS_SUCCEEDED = 'LOAD_POSTCOMMENTS_SUCCEEDED';
export const LOAD_POSTCOMMENTS_FAILED = 'LOAD_POSTCOMMENTS_FAILED';

export const REPLY_POST_STARTED = 'REPLY_POST_STARTED';
export const REPLY_POST_SUCCEEDED = 'REPLY_POST_SUCCEEDED';
export const REPLY_POST_FAILED = 'REPLY_POST_FAILED';