export const LOAD_BLOGCOMMENTS_STARTED = 'LOAD_BLOGCOMMENTS_STARTED';
export const LOAD_BLOGCOMMENTS_SUCCEEDED = 'LOAD_BLOGCOMMENTS_SUCCEEDED';
export const LOAD_BLOGCOMMENTS_FAILED = 'LOAD_BLOGCOMMENTS_FAILED';