export const LOAD_POSTS_STARTED = 'LOAD_POSTS_STARTED';
export const LOAD_POSTS_SUCCEEDED = 'LOAD_POSTS_SUCCEEDED';
export const LOAD_POSTS_FAILED = 'LOAD_POSTS_FAILED';

export const LOAD_POST_STARTED = 'LOAD_POST_STARTED';
export const LOAD_POST_SUCCEEDED = 'LOAD_POST_SUCCEEDED';
export const LOAD_POST_FAILED = 'LOAD_POST_FAILED';

export const UPDATE_POST_STARTED = "UPDATE_POST_STARTED";
export const UPDATE_POST_SUCCEEDED = "UPDATE_POST_SUCCEEDED";
export const UPDATE_POST_FAILED = "UPDATE_POST_FAILED";